# Generated by Django 4.2.5 on 2023-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0002_post_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blogger App', max_length=255),
        ),
    ]
