# Generated by Django 4.2.5 on 2023-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
