services:
  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - web_static:/code/var/www/blogger.com/static/
    ports:
      - "8888:80"
    depends_on:
      -  web
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput 
      && uwsgi --ini blog.ini"
    volumes:
      - web_static:/code/var/www/blogger.com/static/
#    ports:
#      - "8000:8000"
    expose:
      - "3000"
    env_file:
      - ./.env


volumes:
  web_static: